version: "3.3"

services:
  faredge-data-router-and-preprocessor:
    container_name: "faredge-data-router-and-preprocessor"
    build: .
    volumes:
      - ./:/faredge/data-router-and-preprocessor
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    links:
      - faredge-device-registry
    command: /faredge/data-router-and-preprocessor/node_modules/.bin/nodemon --inspect --exec 'node' server.js

  faredge-device-registry:
    container_name: "faredge-device-registry"
    image: mongo:3.6.4
    volumes:
      - ./data/db:/data/db
    ports:
      - "${MONGODB_PORT}:27017"
