version: "3.3"

services:
  faredge-open-api-for-analytics:
    container_name: "faredge-open-api-for-analytics"
    build: .
    volumes:
      - ./:/faredge/open-api-for-analytics
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    links:
      - faredge-data-storage
    command: /faredge/open-api-for-analytics/node_modules/.bin/nodemon --inspect --exec 'node' server.js

  faredge-data-storage:
    container_name: "faredge-data-storage"
    image: mongo:3.6.4
    volumes:
      - ./data/db:/data/db
    ports:
      - "${MONGODB_PORT}:27017"
