version: "3.3"

services:
  mqtt-random-data-publisher:
    container_name: "mqtt-random-data-publisher"
    build: .
    volumes:
      - ./:/faredge/mqtt-random-data-publisher
    env_file: .env
    links:
      - mqtt-broker
    command: /faredge/mqtt-random-data-publisher/node_modules/.bin/nodemon --inspect --exec 'node' index.js

  mqtt-broker:
    container_name: "mqtt-broker"
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      
  mqtt-subscriber:
    container_name: "mqtt-subscriber"
    image: aksakalli/mqtt-client:latest
    restart: always
    links:
      - mqtt-broker
    command: sub -h mqtt-broker -t "#" -v

volumes:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  